### ISSUE TITLE
Newspaper Code Structure

### ISSUE THREAD

**Issue by mateatslc** [joshburgess/not-awesome-es6-classes#3]
You might want to add [**Newspaper Code Structure**](https://medium.com/@kentcdodds/newspaper-code-structure-8b4616af9539#.7xanupele) by @kentcdodds to the [Articles & Blog Posts](https://github.com/joshburgess/not-awesome-es6-classes#articles--blog-posts) section. I'll put a PR in place if interested.

**Comment by joshburgess** [comment]
I don't really think that this article is closely related enough to the topic to be included. It mentions classes, yes, but it's not really about the same topic.

**Comment by mateatslc** [comment]
No problem, closing this.

**Comment by kentcdodds** [comment]
Cheers!
