### ISSUE TITLE
Resource for dealing with EventEmitters

### ISSUE THREAD

**Issue by emschwartz** [joshburgess/not-awesome-es6-classes#6]
I appreciate the alternatives to classes presented here. Do you have any suggestions on best practices for dealing with `EventEmitter`s?

**Comment by joshburgess** [comment]
Thanks. Sorry, I do not. This repo was meant to be about a few very general & commonly discussed topics in JS: prototypal inheritance vs classical inheritance, whether or not ES6 classes really add any value to the language, alternatives to the constructor + new pattern like OLOO (Objects Linked to Other Objects), etc.... I have seen people starting to use classes to extend EventEmitters, sadly. This is one of the things that people against the idea of ES6 classes were worried about. When a language offers a feature, no matter how divisive and inferior it might be, many people will start latching onto it for everything they do... :[

**Comment by emschwartz** [comment]
Just to clarify: do you have an issue with the EventEmitter concept, or just with using classes to extend EventEmitter? I asked the question because I was largely convinced by the articles offering alternatives to classes but didn't see a way to deal with events in those frameworks.

**Comment by joshburgess** [comment]
No, nothing against EventEmitter. Sorry, I don't really have much to offer other than noticing people have been using class to extend it lately.
